name: htsinfer
channels:
  - defaults
dependencies:
  - coverage>=5.3
  - coveralls>=3.0.0
  - flake8>=3.8.4
  - mypy>=0.782
  - pip=20.2.3
  - pylint>=2.4.4
  - pytest>=6.1.0
  - pip:
    - python-semantic-release>=7.15.0
