name: htsinfer
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.78
  - pip=20.2.3
  - pydantic=1.8.1
  - pandas=1.2.3
  - python=3.8.5
  - kallisto=0.46.1
  - pip:
    - -e .
