name: htsinfer
channels:
  - defaults
  - bioconda
dependencies:
  - pip>=20.2.3
  - python>=3.6, <=3.10
  - star>=2.7.6
  - pip:
    - biopython>=1.78
    - pandas>=1.0.5
    - pydantic>=1.8.1
    - pyahocorasick>=1.4.0
    - pysam>=0.16.0
    - -e .
