name: htsinfer
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.78
  - star=2.7.6
  - pysam=0.16.0
  - pip=20.2.3
  - pydantic=1.8.1
  - python=3.8.5
  - pip:
    - -e .
