name: htsinfer
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.79
  - star=2.7.10a
  - pysam=0.19.0
  - pip=22.1
  - pandas=1.4.2
  - pydantic=1.9.0
  - pyahocorasick=1.4.4
  - python=3.8.5
  - pip:
    - -e .
