name: htsinfer
channels:
  - conda-forge
  - bioconda
dependencies:
  - biopython >=1.78
  - coverage >=5.3
  - cutadapt >=3.5, <=4.2
  - flake8 >=3.8.4
  - kallisto >=0.46.1, <= 0.48.0
  - mypy >=0.782
  - numpy >=1.22, <1.25
  - pandas >=1.3.5, <1.4.0
  - pip >=20.2.3
  - pyahocorasick >=1.4.0
  - pydantic >=2, <3
  - pylint >=2.4.4
  - pysam >=0.16.0
  - pytest >=6.1.0
  - python >=3.8, <=3.10
  - python-semantic-release >=8
  - sphinx-rtd-theme
  - star >=2.7.6
  - pip:
    - -e .
