name: htsinfer
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython>=1.78
  - kallisto>=0.46.1
  - pandas>=1.0.5
  - pip>=20.2.3
  - pyahocorasick>=1.4.0
  - pydantic>=1.8.1
  - pysam>=0.16.0
  - python>=3.6, <=3.10
  - star>=2.7.6
  - cutadapt>=3.5
  - pip:
    - -e .
