name: htsinfer
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - biopython=1.78
  - pip=20.2.3
  - pandas=1.0.5
  - pydantic=1.8.1
  - pyahocorasick=1.4.0
  - python>=3.6, <=3.10
  - pip:
    - -e .
