name: semantic-release

on: [push, pull_request]

jobs:

  publish-debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup miniconda & htsinfer root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: htsinfer
          auto-activate-base: false

      - name: Update htsinfer env with dev. packages
        run: conda env update --file environment-dev.yml

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Publish the package (DEBUG mode)
        run: |
          git config --global user.name "semantic-release (via GH Actions)"
          git config --global user.email "semantic-release@actions"
          semantic-release publish -v DEBUG
