name: unit-testing

on: [push, pull_request]

jobs:

  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    name: Python ${{ matrix.python-version }}

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup miniconda & htsinfer root env
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: htsinfer
          auto-activate-base: false

      - name: Update htsinfer env with dev. packages
        run: conda env update --file environment-dev.yml

      - name: Display all miniconda & env info
        run: |
          conda info -a
          conda list

      - name: Test code coverage
        run: coverage run --source htsinfer -m pytest

      - name: Upload code coverage to coveralls
        run: coveralls
